name: deploy

# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GCE_PROJECT: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: development-01
  GCE_INSTANCE_ZONE: asia-northeast1-c

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy
        run: |
          gcloud compute scp --recurse \
          * development:~
