name: deploy

# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GCE_PROJECT: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: development-01
  GCE_INSTANCE_ZONE: asia-northeast1-c

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@master

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions-hub/gcloud@271.0.0
        env:
          PROJECT_ID: ${{secrets.GCE_PROJECT}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
        with:
          args: compute scp --zone="asia-northeast1-c" --recurse * development-01:~/deploy-test
      # # Setup gcloud CLI
      # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #   with:
      #     version: "270.0.0"
      #     service_account_email: ${{ secrets.SA_EMAIL }}
      #     service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      # - name: Deploy
      #   run: |
      #     gcloud compute scp --recurse \
      #     * development:~
